version: '3.9'

# Network
networks:
  web_network:
    name: reactdockermui_network
    driver: bridge

# Services
services:
  # React App Service
  reactapp_dev:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: reactappmui_dev
    restart: always
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules # Bookmarked volume
    ports:
      - 5173:5173
    environment: 
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network
  reactapp_prod:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: reactappmui_prod
    expose:
      - 4173
    networks:
      - web_network
  nginx:
    depends_on:
      - reactapp_prod
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web_network